# Generated by Django 2.0.4 on 2018-05-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_attendees',
            field=models.BooleanField(default=True),
        ),
    ]
