# Generated by Django 2.0.4 on 2018-06-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_simplify_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='signup_open',
            field=models.BooleanField(default=True),
        ),
    ]
