# Generated by Django 2.0 on 2021-11-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_signup_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='give_a_talk',
            field=models.BooleanField(default=False, verbose_name='I would like to give a talk'),
        ),
    ]
