# Generated by Django 3.2.9 on 2021-11-11 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_formfield_clean_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='signup_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.formpage', verbose_name='Signup Form'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='signup_open',
            field=models.BooleanField(default=False, help_text='Create a Signup Form (Form Page) above instead.', verbose_name='Signup open (old hard-coded form)'),
        ),
    ]
